services:
  frontend-web:
    build: ./frontend
    image: rishingm/livescore-frontend:latest
    ports:
      - "8888:80"
    depends_on:
      - backend-api
    networks:
      - app-network

  backend-api:
    build: ./backend
    image: ${DOCKERHUB_USERNAME}/livescore-backend:latest
    ports:
      - "8000:8000"   # ✅ expose backend to host
    environment:
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
