version: '3.7'

services:
  frontend-web:
    build: ./frontend
    image: ${DOCKERHUB_USERNAME}/livescore-frontend:latest
    ports:
      - "8090:80" # use 8090 on host → 80 inside container
    depends_on:
      - backend-api

  backend-api:
    build: ./backend
    image: ${DOCKERHUB_USERNAME}/livescore-backend:latest
